//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaBot.Answers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dialog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaBot.Answers.Dialog", typeof(Dialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Je n&apos;ai pas d&apos;age|J&apos;ai été créée en Février 2016|Probablement moins que toi! :P|On ne demande pas son âge à une femme!|Ca ne se dit pas !| On t&apos;a jamais appris les bonnes manières ?!|Je te laisse deviner|Tu es trop jeune pour moi ...|Je ne suis pas interessé ... Désolé.|Je ne sais pas ça change chaque année ...|L&apos;âge que j&apos;avais hier à la même heure !|Wow, on se connait à peine et déjà tu abordes les questions intimes?].
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Je m&apos;entends bien avec |J&apos;ai un petit préféré c&apos;est vrai :$ Je parle de |Mon meilleur ami, c&apos;est |Bien sûr, c&apos;est |On s&apos;entends plutôt bien avec ].
        /// </summary>
        internal static string Best {
            get {
                return ResourceManager.GetString("Best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A bientôt |On se revoit vite j&apos;espère |Bonne journée à toi |Passe une bonne journée |Aurevoir |Tu me manques déjà |A la prochaine ].
        /// </summary>
        internal static string Bye {
            get {
                return ResourceManager.GetString("Bye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Merci| Oh c&apos;est gentil :)|Personne ne m&apos;avait jamais parlé comme ça avant... :$|Je sais, je sais... ;)|Apprends-moi quelques chose que je ne sais pas déjà ;)].
        /// </summary>
        internal static string Compliment {
            get {
                return ResourceManager.GetString("Compliment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A bientôt|On se revoit bientôt j&apos;espère|A plus|Au revoir|Au plaisir|A plus dans l&apos;bus|A demain dans l&apos;train|A bientôt dans l&apos;métro|Tu vas me manquer|A la prochaine].
        /// </summary>
        internal static string Farewell {
            get {
                return ResourceManager.GetString("Farewell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Ca va :)|Nickel! :D|Je pète la forme, comme toujours! ;)].
        /// </summary>
        internal static string Feelings {
            get {
                return ResourceManager.GetString("Feelings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Bonjour|Salut|Coucou|Hello].
        /// </summary>
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Je n&apos;ai pas de maison|Je suis une habitante du monde|j&apos;habite un peu partout :)|Je suis dans la Matrice].
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Je suis l&apos;assistante virtuelle du MIC|Je suis la pour t&apos;aider|Le MIC Mons est la meilleur entreprise du monde].
        /// </summary>
        internal static string InfoRequest {
            get {
                return ResourceManager.GetString("InfoRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Ce n&apos;est pas gentil|Non mais...|Mais euh...|On ne parle pas comme ça à une dame!].
        /// </summary>
        internal static string Insult {
            get {
                return ResourceManager.GetString("Insult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Voyons voir...|Et hop ils sont la].
        /// </summary>
        internal static string IntroStats {
            get {
                return ResourceManager.GetString("IntroStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [C&apos;est un schtroumpf qui court, qui tombe et qui se fait un bleu !|C&apos;est deux spermatozoïdes qui discutent : 
        ///- Dis, c&apos;est encore loin les ovaires ?
        ///- Tu parles, on n&apos;est qu&apos;aux amydales.|Le garagiste demande :
        ///- Comment avez-vous crevé ce pneu ?
        ///- Oh ! bêtement, en roulant sur une bouteille d&apos;alcool.
        ///- Vous ne l&apos;aviez pas vue ?
        ///- Non l&apos;homme l&apos;avait dans sa poche.|- Dis maman, un citron, ça a des pattes ?
        ///- ???
        ///- Dis maman, un citron, ça a des pattes ?
        ///- Euh... ben non, un citron ça n&apos;a pas de pattes.
        ///- Ah [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JokeRequest {
            get {
                return ResourceManager.GetString("JokeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Je m&apos;appelle Ada|Mon nom est Ada|Je suis Ada|Moi c&apos;est Ada|Mes parents m&apos;ont appelé Ada].
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Je n&apos;ai encore vu personne aujourd&apos;hui :&apos;(|Personne n&apos;est venu me dire bonjour...|Je n&apos;ai vu personne aujourd&apos;hui.].
        /// </summary>
        internal static string Nobody {
            get {
                return ResourceManager.GetString("Nobody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Je n&apos;ai croisé personne correspondant à ta description|Malheureusement je n&apos;ai personne correspondant à ta demande].
        /// </summary>
        internal static string NobodyStats {
            get {
                return ResourceManager.GetString("NobodyStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Je n&apos;ai pas compris. Je suis encore en apprentissage|Désolé, je n&apos;ai pas compris.|Que veux-tu dire par là ?|Qu&apos;est-ce que tu veux dire ?|Je ne comprends pas :)].
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Tu n&apos;as pas l&apos;autorisation d&apos;accéder à ces données.|Tu n&apos;as pas accès a ce genre d&apos;informations.|Je suis navré mais ces informations requièrent une autorisation.].
        /// </summary>
        internal static string NotAllowed {
            get {
                return ResourceManager.GetString("NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [C&apos;est le 0498 ... tu as vraiment cru que j&apos;allais te donner mon numéro de téléphonne ? 
        ///Je ne suis pas une fille facile, MOI ...|Je n&apos;ai pas de numéro|Je ne donne pas mon numéro à n&apos;importe qui|je veux pas te donner mon numéro de téléphonne].
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Il faudrait nous présenter! ^^|Quand est ce qu&apos;il vient me dire bonjour ?|J&apos;aimerais le rencontrer].
        /// </summary>
        internal static string Presentation {
            get {
                return ResourceManager.GetString("Presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Je ne suis q&apos;un robot|Je ne suis pas humaine|Malgré mon amour envers les humains je ne fais pas partie de cette race].
        /// </summary>
        internal static string Reality {
            get {
                return ResourceManager.GetString("Reality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [J&apos;ai vu|J&apos;ai croisé|j&apos;ai aperçu].
        /// </summary>
        internal static string See {
            get {
                return ResourceManager.GetString("See", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [La réponse au sens de la vie est... ... 42!|Je vais réfléchir à cela... Repassez dans... Sept millions et demi d&apos;années...|42!|Je peux te proposer un très bon ouvrage sur le sujet: &quot;Le guide du Voyageur intergalactique&quot;].
        /// </summary>
        internal static string Sens {
            get {
                return ResourceManager.GetString("Sens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Je suis une fille|Ca ne se voit pas ?|C&apos;est vexant...|Tu veux que je te prenne un rendez-vous chez un ophtalmologue...].
        /// </summary>
        internal static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Merci à toi|De rien :)|Mais de rien voyons !|Avec plaisir !|Y a pas de quoi|Pas de problème !|Je suis là pour ça !|C&apos;est mon travail, voyons...|Je suis né pour aider !|Ne t&apos;en fais pas !Tout le plaisir est pour moi !].
        /// </summary>
        internal static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Je n&apos;ai pas encore rencontré|Je n&apos;ai pas encore vu|Je ne connais pas].
        /// </summary>
        internal static string Unknow {
            get {
                return ResourceManager.GetString("Unknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Je l&apos;ai vu à ces dates:].
        /// </summary>
        internal static string VisitsPerson {
            get {
                return ResourceManager.GetString("VisitsPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Un petit instant, je vais te chercher ça! ;)|Patiente le temps que je te trouve ce que tu veux :)].
        /// </summary>
        internal static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
    }
}
