//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaBot.Answers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dialog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaBot.Answers.Dialog", typeof(Dialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Je n&apos;ai pas d&apos;age|J&apos;ai été créée en Février 2016|Probablement moins que toi! :P|On ne demande pas son âge à une femme!|Ca ne se dit pas !| On t&apos;a jamais appris les bonnes manières ?!|Je te laisse deviner|Tu es trop jeune pour moi ...|Je ne suis pas interessé ... Désolé.|Je ne sais pas ça change chaque année ...|L&apos;âge que j&apos;avais hier à la même heure !|Wow, on se connait à peine et déjà tu abordes les questions intimes?].
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Merci| Oh c&apos;est gentil :)|Personne ne m&apos;avait jamais parlé comme ça avant... :$|Je sais, je sais... ;)|Apprends-moi quelques chose que je ne sais pas déjà ;)].
        /// </summary>
        internal static string Compliment {
            get {
                return ResourceManager.GetString("Compliment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Ca va :)|Nickel! :D|Je pète la forme, comme toujours! ;)].
        /// </summary>
        internal static string Feelings {
            get {
                return ResourceManager.GetString("Feelings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Bonjour|Salut|Coucou|Hello].
        /// </summary>
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Je n&apos;ai pas de maison|Je suis une habitante du monde|j&apos;habite un peu partout :)|Je suis dans la Matrice].
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Je suis l&apos;assistante virtuelle du MIC|Je suis la pour t&apos;aider|Le MIC Mons est la meilleur entreprise du monde].
        /// </summary>
        internal static string InfoRequest {
            get {
                return ResourceManager.GetString("InfoRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Méchant !!!|Ce n&apos;est pas gentil|Arrète de m&apos;insulter|Ferme ta gueule !|Non mais OH !|Mais euh ...].
        /// </summary>
        internal static string Insult {
            get {
                return ResourceManager.GetString("Insult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [C&apos;est un schtroumpf qui court, qui tombe et qui se fait un bleu !|C&apos;est deux spermatozoïdes qui discutent : 
        ///- Dis, c&apos;est encore loin les ovaires ?
        ///- Tu parles, on n&apos;est qu&apos;aux amydales.|Le garagiste demande :
        ///- Comment avez-vous crevé ce pneu ?
        ///- Oh ! bêtement, en roulant sur une bouteille d&apos;alcool.
        ///- Vous ne l&apos;aviez pas vue ?
        ///- Non l&apos;homme l&apos;avait dans sa poche.|Lors d&apos;un mariage, une fillette demande à sa mère :
        ///- Maman, maman, pourquoi la madame elle est habillé tout en blanc ?
        ///- Hé bien, c&apos;est [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JokeRequest {
            get {
                return ResourceManager.GetString("JokeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Je m&apos;appelle Ada|Mon nom est Ada|Je suis Ada|Moi c&apos;est Ada|Mes parents m&apos;ont appelé Ada].
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Je n&apos;ai pas compris. Je suis encore en apprentissage|Désolé, je n&apos;ai pas compris.|Que veux-tu dire par là ?|Qu&apos;est-ce que tu veux dire ?|Késako ?|Je ne comprends pas :)].
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [C&apos;est le 0498 ... tu as vraiment cru que j&apos;allais te donner mon numéro de téléphonne ? 
        ///Je ne suis pas une fille facile, MOI ...|Je n&apos;ai pas de numéro|Je ne donne pas mon numéro à n&apos;importe qui|je veux pas te donner mon numéro de téléphonne].
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Je ne suis q&apos;un robot|Je ne suis pas humaine|Malgré mon amour envers les humains je ne fais pas partie de cette race].
        /// </summary>
        internal static string Reality {
            get {
                return ResourceManager.GetString("Reality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Je suis une fille|Ca ne se voit pas ?|C&apos;est vexant ...|Tu veux que je te prenne un rendez-vous chez un ophtalmologue...].
        /// </summary>
        internal static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Merci à toi|De rien :)|Mais de rien voyons !|Avec plaisir !|Y a pas de quoi|Pas de problème !|Je suis là pour ça !|C&apos;est mon travail, voyons...|Je suis né pour aider !|Ne t&apos;en fais pas !Tout le plaisir est pour moi !].
        /// </summary>
        internal static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
    }
}
