// <auto-generated />
namespace AdaWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PictureOK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PictureOK));
        
        string IMigrationMetadata.Id
        {
            get { return "201703171146235_PictureOK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
